"""
Render snapshot agents as a single instanced point cloud.

Uses a UsdGeom.PointInstancer rather than one prim per citizen: 300+ separate
spheres cost real time to draw and bloat the stage, while an instancer is one
prim regardless of population. This matters on an 8 GB laptop GPU.

Agents are binned by stress into a handful of coloured prototypes instead of
carrying a per-instance colour primvar, because prototype indices render
identically everywhere while varying primvars on instancers do not.

Run:
    python presentation/agents_instancer.py phase3/mock_data/mock_stress.json
    python presentation/agents_instancer.py <snapshot> --metric heat_exposure
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from pxr import Gf, Sdf, Usd, UsdGeom, Vt

sys.path.insert(0, str(Path(__file__).resolve().parent))
from recolor_paths import ramp  # noqa: E402  (shared colour ramp)

OUT = Path(__file__).resolve().parent / "scene" / "generated" / "agents.usda"

BINS = 5          # stress buckets -> prototype spheres
MARKER_RADIUS = 1.6   # metres; readable at ProblemZone zoom, not blobby at street level
MARKER_LIFT = 0.9     # raise markers off the 0.1 m path ribbons


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("snapshot", type=Path)
    ap.add_argument("--metric", default="stress", help="agent field to colour by (default: stress)")
    ap.add_argument("--radius", type=float, default=MARKER_RADIUS)
    args = ap.parse_args()

    snap = json.loads(args.snapshot.read_text(encoding="utf-8"))
    agents = snap.get("agents")
    if not agents:
        raise SystemExit(f"{args.snapshot}: no 'agents' array")

    layer = Sdf.Layer.CreateAnonymous(".usda")
    stage = Usd.Stage.Open(layer)
    UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.z)
    UsdGeom.SetStageMetersPerUnit(stage, 1.0)
    stage.SetDefaultPrim(stage.OverridePrim("/World"))

    inst = UsdGeom.PointInstancer.Define(stage, "/World/Agents")
    inst.GetPrim().SetDocumentation(
        f"Synthetic citizens from {args.snapshot.name}, coloured by '{args.metric}'. "
        "Generated by presentation/agents_instancer.py."
    )

    proto_paths = []
    for i in range(BINS):
        t = i / (BINS - 1)
        p = f"/World/Agents/Prototypes/bin{i}"
        sphere = UsdGeom.Sphere.Define(stage, p)
        sphere.CreateRadiusAttr(float(args.radius))
        sphere.CreateDisplayColorAttr([Gf.Vec3f(*ramp(t))])
        # Prototypes must not draw on their own; only instances of them do.
        UsdGeom.Imageable(sphere).CreateVisibilityAttr(UsdGeom.Tokens.inherited)
        proto_paths.append(Sdf.Path(p))
    UsdGeom.Scope.Define(stage, "/World/Agents/Prototypes")

    positions, indices = [], []
    missing = 0
    for a in agents:
        v = a.get(args.metric)
        if v is None:
            missing += 1
            v = 0.0
        b = min(BINS - 1, max(0, int(float(v) * BINS)))
        indices.append(b)
        positions.append(Gf.Vec3f(float(a["x"]), float(a["y"]), float(a.get("z", 0.0)) + MARKER_LIFT))

    inst.CreatePositionsAttr(Vt.Vec3fArray(positions))
    inst.CreateProtoIndicesAttr(Vt.IntArray(indices))
    inst.CreatePrototypesRel().SetTargets(proto_paths)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    stage.GetRootLayer().documentation = (
        f"Generated by presentation/agents_instancer.py from {args.snapshot.name}. Do not hand-edit."
    )
    layer.Export(str(OUT))

    hist = [indices.count(i) for i in range(BINS)]
    print(f"wrote {OUT}")
    print(f"  {len(positions)} agents as 1 PointInstancer, {BINS} prototypes"
          + (f" ({missing} missing '{args.metric}')" if missing else ""))
    print(f"  bins low->high: {hist}")


if __name__ == "__main__":
    main()
