"""
Colour the pedestrian network by a simulated metric.

Reads a canonical v1 visualization snapshot (docs/INTEGRATION_CONTRACT.md),
looks each edge id up in the Phase 2 edge registry, and writes per-prim
displayColor overrides to phase9/scene/generated/path_colors.usda.

Geometry and semantics are never touched - this only authors an override
layer, so reverting is deleting one file.

Run:
    python phase9/recolor_paths.py phase3/mock_data/mock_stress.json
    python phase9/recolor_paths.py <snapshot> --metric crowding
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

from pxr import Sdf, Usd, UsdGeom

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "phase2" / "scene" / "edge_registry.json"
OUT = Path(__file__).resolve().parent / "scene" / "generated" / "path_colors.usda"

# Cool -> hot ramp. Deliberately NOT red/green: that pair is the most common
# colourblind confusion and these ribbons are thin. Luminance falls as severity
# rises, so the ramp still reads in greyscale or on a washed-out projector.
RAMP: List[Tuple[float, Tuple[float, float, float]]] = [
    (0.00, (0.55, 0.72, 0.85)),   # calm      - light blue
    (0.35, (0.85, 0.88, 0.70)),   # noticeable- pale yellow
    (0.65, (0.95, 0.65, 0.25)),   # bad       - orange
    (1.00, (0.75, 0.10, 0.12)),   # critical  - deep red
]

UNMAPPED = (0.30, 0.31, 0.33)  # edges the snapshot says nothing about


def ramp(t: float) -> Tuple[float, float, float]:
    t = max(0.0, min(1.0, t))
    for (t0, c0), (t1, c1) in zip(RAMP, RAMP[1:]):
        if t <= t1:
            f = 0.0 if t1 == t0 else (t - t0) / (t1 - t0)
            return tuple(a + f * (b - a) for a, b in zip(c0, c1))
    return RAMP[-1][1]


def load_registry() -> Dict[str, dict]:
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    edges = data.get("edges")
    if not isinstance(edges, dict) or not edges:
        raise SystemExit(f"{REGISTRY}: no 'edges' mapping found")
    return edges


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("snapshot", type=Path, help="canonical v1 snapshot JSON")
    ap.add_argument("--metric", default="heat_exposure",
                    help="edge metric to colour by (default: heat_exposure)")
    ap.add_argument("--dim-unmapped", action="store_true",
                    help="grey out edges the snapshot does not mention")
    args = ap.parse_args()

    snap = json.loads(args.snapshot.read_text(encoding="utf-8"))
    edge_metrics = snap.get("edges") or {}
    if not edge_metrics:
        raise SystemExit(f"{args.snapshot}: no 'edges' block - is this a canonical snapshot? "
                         "Simulation/urbantwin_demo_output.json is a behavioural report, "
                         "not a visualization snapshot.")

    registry = load_registry()

    # city_id guards against colouring the wrong city with valid-looking ids.
    reg_city = json.loads(REGISTRY.read_text(encoding="utf-8")).get("city_id")
    snap_city = snap.get("city_id")
    if snap_city and reg_city and snap_city != reg_city:
        raise SystemExit(f"city_id mismatch:\n  snapshot {snap_city}\n  registry {reg_city}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    layer = Sdf.Layer.CreateAnonymous(".usda")
    stage = Usd.Stage.Open(layer)
    UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.z)
    UsdGeom.SetStageMetersPerUnit(stage, 1.0)
    stage.SetDefaultPrim(stage.OverridePrim("/World"))

    coloured, missing_metric, unknown = 0, 0, []
    values = []

    for edge_id, info in registry.items():
        prim_path = info.get("prim_path")
        if not prim_path:
            continue
        metrics = edge_metrics.get(edge_id)
        if metrics is None:
            if args.dim_unmapped:
                prim = stage.OverridePrim(prim_path)
                UsdGeom.Gprim(prim).CreateDisplayColorAttr([UNMAPPED])
                missing_metric += 1
            continue
        if args.metric not in metrics:
            unknown.append(edge_id)
            continue
        v = float(metrics[args.metric])
        values.append(v)
        prim = stage.OverridePrim(prim_path)
        UsdGeom.Gprim(prim).CreateDisplayColorAttr([ramp(v)])
        coloured += 1

    if unknown:
        raise SystemExit(f"metric '{args.metric}' missing on {len(unknown)} edges "
                         f"(e.g. {unknown[:3]}). Available: "
                         f"{sorted(next(iter(edge_metrics.values())).keys())}")

    stage.GetRootLayer().documentation = (
        f"Generated by phase9/recolor_paths.py from {args.snapshot.name} "
        f"metric={args.metric}. Do not hand-edit."
    )
    layer.Export(str(OUT))

    print(f"wrote {OUT}")
    print(f"  coloured {coloured} edges by '{args.metric}'"
          + (f", dimmed {missing_metric} unmapped" if args.dim_unmapped else ""))
    if values:
        print(f"  metric range {min(values):.2f} .. {max(values):.2f}")
    print("  legend:", "  ".join(f"{t:.2f}=rgb{tuple(round(c,2) for c in col)}" for t, col in RAMP))


if __name__ == "__main__":
    main()
